apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  template:
    spec:
      containers:
        - name: sample-app
          image: myregistry.azurecr.io/sample-app:latest
          imagePullPolicy: Always
